name: Generate Doxygen Documentation for EBS piolib Formatted Projects

on:
  workflow_call:
    inputs:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Clone docbuilder repository
        run: git clone https://github.com/ebs-universe/docbuilder-piolib.git docbuilder

      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: 3.x

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxyfile
        run: python docbuilder/generate_doxyfile.py

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
